// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aupbrobbgzqjunjzqeaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1cGJyb2JiZ3pxanVuanpxZWF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNjYyMzYsImV4cCI6MjA3MTg0MjIzNn0.ZGsIEHZTRMIZCTGwF5_ToC5hlZrjkX6kD12D-Ph6qdg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});